### ISSUE TITLE
Coupons of percantage type in MultisafePay Control

### ISSUE THREAD

**Issue by LMG-Jeffy** [MultiSafepay/Opencart#11]
I don't know if it's a bug or a feature request, but we're having trouble displaying coupons in the Multisafepay Control dasbboard. It comes with coupons that are valid for all products and thus have no product or category restriction.

## Situation
Coupons is sorted higher by order totals than taxes. Type of coupons used is: Percentage for all items in the order. If we put the Coupons before the tax totals then fixed price coupons will be applied proportionally to all products. Which can come at negative prices.

Coupon = `FIXED_TYPE` 
is_order_lower_than_taxes = `true`
![image](https://user-images.githubusercontent.com/17408698/219951708-f15bf0a6-4a0a-4115-a9cf-a21a94b11d2c.png)

Coupon = `FIXED_TYPE` 
is_order_lower_than_taxes = `false`
![image](https://user-images.githubusercontent.com/17408698/219951796-64fc8255-cff9-445d-a8e7-7a3727ad061a.png)

Coupon = `PERCENTAGE_TYPE` 
is_order_lower_than_taxes = `true`
![image](https://user-images.githubusercontent.com/17408698/219951888-0e05610f-4a21-4b4c-896c-698fb1a6ad75.png)

Coupon = `PERCENTAGE_TYPE` 
is_order_lower_than_taxes = `false`
**Discount is not shown and calculated at all. Order ammout of € 891,65 had been paid en is the correct total**
![image](https://user-images.githubusercontent.com/17408698/219951959-4c6f52da-7011-4b44-8d40-e00c7780b9ee.png)

## Result
Percentage discount is not displayed correctly in the Multisafepay Control panel.

## Cause
Percent off all products is not applied if the order comes after the tax totals.

## Solution
Percent discount that applies to all products should always be executed regardless of whether this order is higher or lower than the tax totals.

Coupon = `PERCENTAGE_TYPE` 
is_order_lower_than_taxes = `false`
![image](https://user-images.githubusercontent.com/17408698/219952124-c808c565-b142-4695-ac5e-ac6a6db7220c.png)

I felt so free to make a pull request for this. If this is not the correct way of working, I would like to apologize.

**Comment by danielcivit** [comment]
Hello @LMG-Jeffy 

Thanks for your report, a good explanation, and deep inside the code to find  the cause.  
We will be looking into this issue in a short term, and get back to you with more information.

**Comment by Miguel-MultiSafepay** [comment]
Hi @LMG-Jeffy 

We have been looking into this issue.

Certainly, we never considered a case in which the coupon needs to be applied after taxes, because in those cases the taxes are being overestimated, according to our criteria.

Please, consider the following screenshot  where the coupon is being applied after taxes.
![Captura de pantalla 2023-02-20 a las 16 11 47](https://user-images.githubusercontent.com/104830395/220143999-d18c6bff-38f3-4943-9869-c794fa2c0b05.png)


And this one, where the coupon is being applied before taxes, which is what we are using in our payment system.
![Captura de pantalla 2023-02-20 a las 16 26 01](https://user-images.githubusercontent.com/104830395/220146295-334dd956-b06a-42ba-b474-05a5ba070534.png)

======

On the other hand, it is true that OpenCart offers this kind of possibility, namely to interchange the position between coupon and taxes (and other elements).  Please, could you double confirm if this is the result you want to get, namely coupon applied after taxes?

If that's the case, of course we will continue looking for a solution for this, as you said, we will consider this a feature request not a bug. 

Also, at this moment, we tested your PR and so far, it seems your proposal is wrong, however don't worry about that, we will work to make this possible.

**Comment by danielcivit** [comment]
Hi @LMG-Jeffy 

We are closing this ticket due to inactivity, when we were waiting for a response about the expected behavior.
Don't hesitate to reopen this thread if you need it. 

Thanks.
