### ISSUE TITLE
MSP payment screen is not displaying correct tax when credits are used!

### ISSUE THREAD

**Issue by dennisbuijsgmailcom** [MultiSafepay/Opencart#15]
Hi

See attachment.
![msp](https://github.com/MultiSafepay/opencart/assets/6247951/955047b3-7779-415e-9d41-0e834d6b8a8b)

When I have an order with credits in it, I see that in the MSP overview, the tax calculation is wrong. The tax calculation is done over the subtotal amount of 1,95 but with credits of -1,95, there is no tax on the products. 
So only tax on the shipping costs of 6 euro must be calculated, is 1,26.

When I go forward with the payment, the amount to pay IS correct 7,26.

Can this be fixed, is this the opencart extension or the MSP page.

Best regards
Dennis

**Comment by danielcivit** [comment]
Hi @dennisbuijsgmailcom 

Thanks for contacting us about this issue. 

Please, could you write us at integration@multisafepay.com? (I would open the ticket on my own, however, we have several email addresses related to you, and I am not sure which one to use)

In that channel, we will be able to ask you for more sensitive information in a private way. So we can take a look at your case, and explore where is the problem. 

Thanks.

**Comment by danielcivit** [comment]
Hi Dennis. 

I was looking for a ticket related to this issue in our support application. It seems we haven't heard anything else from you about this issue. 

I am closing now this one because of inactivity, but please feel free to reopen it, or send us more details via email, and we will continue looking into this report.
