### ISSUE TITLE
Add support for OpenCart 4.0.2.x & PHP 8.3

### ISSUE THREAD

**Issue by jorimvanhove** [MultiSafepay/Opencart#16]
Starting from OpenCart v4.0.2.x, the `GetMethod` function in payment modules is renamed to `GetMethods`. This is a breaking change and results in an notice while fetching the built-in payment methods, which terminates execution of the event method.

<b>Notice</b>:  Undefined property: Proxy::getMethod in <b>/htdocs/extension/multisafepay/system/library/multisafepayevents.php</b> on line <b>102</b>

The result is that no MultiSafePay payment methods are displayed in the checkout.

See https://github.com/opencart/opencart/blame/fa8ecb37df3ce9894f75465a5b40ff41b48b8f5f/upload/extension/opencart/catalog/model/payment/cod.php#L4

Affected plugin version: 1.3.0 (is this the correct repo?)

**Comment by danielcivit** [comment]
Hi @jorimvanhove .

Thanks for your comment and contacting us. 

- This module - repository supports OpenCart 2.x.x.x - 3.x.x.x
- The module - repository supporting OpenCart 4.x is [this one](https://github.com/MultiSafepay/opencart-4). However at this moment supports only versions 4.0.1.1 or lower. 
  - We have an item in the backlog to support 4.0.2.x but it`s not clear when this will be released. 
  - If you are or represent a MultiSafepay merchant, please contact your business account manager, in that way, your business case will be considered and priorities could change.
 
 
We will keep this ticket open, in order to get back to you once a new version supporting OpenCart 4.0.2.x is released

**Comment by danielcivit** [comment]
Closing this issue. We can follow up on this topic [here](https://github.com/MultiSafepay/opencart-4/issues/1)
