### ISSUE TITLE
In order with zero tax I must still pay tax in MSP payment screen

### ISSUE THREAD

**Issue by dennisbuijsgmailcom** [MultiSafepay/Opencart#4]
Hi

I have just upgraded from a very old MSP OpenCart extensie to the latest. Most things went well and it was quite easy to upgrade.
Now I have one issue.
I have an extension that add 'Reverse charge - VAT exempt' so when a valid vat number is applied, the VAT will be zero.
So I have an order with order total tax with 0 euro, and in the table order_product the product records have all field 'tax' is also
zero.

![msp1](https://user-images.githubusercontent.com/6247951/157289834-ef1a0e65-631f-405a-86b9-c29c0e6e0ed3.png)
![msp2](https://user-images.githubusercontent.com/6247951/157289840-41d37056-7749-49ff-83ee-c1beb02ebbf8.png)

But when I want to pay, in the MultisafePay payment screen I must pay taxes again.
After investigation I see in system\library\multisafepay.php at line 673: $cart_item->addTaxRate((float)$tax_rate); 
This will get the tax_rate from the product table again, and it is ignoring the order_product->tax field that is zero.

I have a workaraound for myself, but maybe its good to also use and check order_product->tax field, or maybe order total tax.

Best regards
Dennis

**Comment by danielcivit** [comment]
Hello @dennisbuijsgmailcom.

Thanks for reach us and inform about this issue. Happy to know you found a temporary workaround to this issue by your self. 

However, the best move here will be check the compatibility of this extension with our extension. Once we fix any issue, you  should be able to continue taking advantaged of next releases and be sure is compatible with your application and business model. 

I wonder if is possible for you open a ticket with us in our internal system and share the details of this extension in order to allow us check compatibility and fix any issue related. 

Could you write an email to support@multisafepay.com? 

This way we can share sensitive information in a secure way and follow up this feature request.  I personally will take it from there.

I will wait for your reply. In the meantime this GitHub issue will remain open.

**Comment by dennisbuijsgmailcom** [comment]
Hi

Tommorow I will sent you the details about my workaround and the details of the extension, I build the VAT extension myself https://shop.openwebcreations.eu/eu-vat-compliant.

Best regards
Dennis

**Comment by danielcivit** [comment]
Hello @dennisbuijsgmailcom.

It looks like a nice extension, and we will be happy to support it and fix any compatibility issue. 

I will wait for your contact in our ticket system.  Maybe you can share with us the files (only for development purposes) to check the details and confirm it will be fixed and fully compatible in our next release. 

Best regards
Daniel

**Comment by danielcivit** [comment]
Hello Dennis. 

We have been spoken in our internal ticket system. As I said there, there is a new release available (3.13.0) in which we take your proposal in order to add compatibility with your extension. 

https://shop.openwebcreations.eu/eu-vat-compliant

However the proposed solution is still incomplete. A couple of changes needs to be done in our extension, using OCMOD, in order to fully support your extension. 

You can download the OCMOD modification from our docs page; where it says "EU VAT Compliant".

https://docs.multisafepay.com/opencart/extensions-and-themes/

If you still experiment any issue, feel free to reopen this Github issue or open any other. 

Thanks.
