### ISSUE TITLE
Shipping tax not applied in OpenCart 2.3

### ISSUE THREAD

**Issue by dennisbuijsgmailcom** [MultiSafepay/Opencart#7]
Hi

I saw that the tax calculation was not working for the tax over the shipping costs. I see in the code function system\library\multisafepay.php -> getShippingTaxClassId() that the tax_class_id is checked from the configuration, thats good :-)
The way you try to check opencart settings for tax_class_id will work for most extensions if they applay to the standard, I can see its working for OpenCart 3 extensions. I am using OpenCart 2.3, so you must use code for most extensions:

$shipping_tax_class_id_key = $shipping_code['0'] . '_tax_class_id'; 

Best regards
Dennis

**Comment by danielcivit** [comment]
Hello @dennisbuijsgmailcom 

We can confirm this issue at this moment affecting OpenCart versions equal or lower than 2.3.x.x.

This bug will be fixed in the next release. At that moment you should be able to upgrade safely our extension without the need to overwrite it again.

In the meantime, this Github issue will remain open. I will get back to you once a new version is released.

Once again, thanks for your feedback and contributions.

**Comment by danielcivit** [comment]
Hello Dennis.

Once again, thanks for report this bug. It has been fixed in our latest release 3.13.0. 

If you still experiment any issue related, feel free to reopen this Github issue or open any other.
